import sys
import time
import json
from prompt_templates import PROMPT_TEMPLATE_English, PROMPT_TEMPLATE_French

def read_tsv(input_file, discard_pos):
    entries, discard_entries = [], []
    with open(input_file, 'r', encoding='utf-8') as f:
        for line in f:
            toks = line.strip().split('\t')
            if len(toks) != 3:
                continue
            if any(toks[1].startswith(pos) for pos in discard_pos):
                discard_entries.append(line.strip())
            else:
                entries.append(toks)
    return entries, discard_entries

def build_prompts(entries, lang='English'):
    if lang == 'English':
        PROMPT_TEMPLATE = PROMPT_TEMPLATE_English
    elif lang == 'French':
        PROMPT_TEMPLATE = PROMPT_TEMPLATE_French

    return [
        PROMPT_TEMPLATE.format(term=term, pos=pos)
        for term, pos, ud in entries
    ]

def batch(iterable, n=1):
    l = len(iterable)
    for i in range(0, l, n):
        yield iterable[i : i + n]

def safe_parse_json(text):
    text = text.strip()

    # Try direct parsing
    try:
        parsed = json.loads(text)
        if isinstance(parsed, list):
            return parsed
    except json.JSONDecodeError:
        pass

    # Try to extract JSON array from text
    start = text.find('[')
    end = text.rfind(']')

    if start != -1 and end != -1 and end > start:
        candidate = text[start:end+1]
        try:
            parsed = json.loads(candidate)
            if isinstance(parsed, list):
                return parsed
        except json.JSONDecodeError:
            pass

    # Fallback: return raw text wrapped in a list for debugging
    return [text]


def main():
    import argparse
    parser = argparse.ArgumentParser(description="vLLM glossary inflection generator", formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument('glossary', type=str)
    parser.add_argument('--lang', type=str, default='English')
    parser.add_argument('--model', type=str, default='/lustre/fsmisc/dataset/HuggingFace_Models/Qwen/Qwen3-32B')
    parser.add_argument('--nopos', nargs='*', default=[], help="Discard inflection of a UD entry if its POS starts with any of these strings")
    parser.add_argument('--ofile', type=str, default=None)
    # Generation params
    parser.add_argument('--temperature', type=float, default=0.0)
    parser.add_argument('--top_p', type=float, default=1.0)
    parser.add_argument('--max_tokens', type=int, default=1024)
    parser.add_argument('--batch_size', type=int, default=32) #number of prompts sent to vllm
    # Model / memory params
    parser.add_argument('--dtype', type=str, default='bfloat16')
    parser.add_argument('--max_model_len', type=int, default=2048)
    parser.add_argument('--max_num_seqs', type=int, default=32) #how many prompts vLLM can process at once internally (process them in chunks internally if needed)
    parser.add_argument('--gpu_memory_utilization', type=float, default=0.95)
    parser.epilog = """- The glossary file should be a TSV with three columns: term, POS, and UD entry (e.g. 'implement', 'verb', 'implement (verb) ||| implémenter').
- The term and POS will be used to fill the {term} and {pos} placeholders in the prompt template.
- Output will be a TSV file with four columns: term POS, inflections, UD entry. 
- inflections is a string with semicolon-separated (;) inflected forms generated by the model, including the original term.
- Duplicates will be removed.
- Usage: $> python udinflector.py --lang English --model /path/to/model UD-enfr.tsv  (file UD-enfr.model_name.inflected.tsv is built)
"""
    args = parser.parse_args()

    if args.ofile is None:
        model_name = args.model.split('/')[-1]
        args.ofile = f"{args.glossary.replace('.tsv','')}.{model_name}.inflected.tsv"

    print(f"Reading glossary: {args.glossary}", file=sys.stderr)
    entries, discard_entries = read_tsv(args.glossary, args.nopos)
    print(f"Read {len(entries)} entries from {args.glossary}", file=sys.stderr)

    prompts = build_prompts(entries, args.lang)

    print(f"Loading model: {args.model}", file=sys.stderr)
    from vllm import LLM, SamplingParams
    tic = time.perf_counter()
    llm = LLM(
        model=args.model,
        dtype=args.dtype,
        max_model_len=args.max_model_len,
        max_num_seqs=args.max_num_seqs,
        gpu_memory_utilization=args.gpu_memory_utilization
    )
    print(f"Loading took {1000*(time.perf_counter()-tic):.2f}ms", file=sys.stderr)

    sampling_params = SamplingParams(
        temperature=args.temperature,
        top_p=args.top_p,
        max_tokens=args.max_tokens,
        repetition_penalty=1.0, #no penalty
        stop=["\n\n", "]"]  # helps truncate unwanted text
    )

    from tqdm import tqdm
    tic = time.perf_counter()
    with open(args.ofile, 'w', encoding='utf-8') as f:
        for batch_idx, prompt_batch in enumerate(tqdm(list(batch(prompts, args.batch_size)), desc="Generating inflections (batches)")):
            results = llm.generate(prompt_batch, sampling_params, use_tqdm=False)
            for idx, res in enumerate(results):
                term_idx = batch_idx * args.batch_size + idx
                initial_term = entries[term_idx][0]
                initial_pos = entries[term_idx][1]
                initial_ud = entries[term_idx][2]
                parsed = safe_parse_json(res.outputs[0].text.strip())
                # Add the initial term, remove duplicates
                for infl in set([initial_term] + parsed):
                    f.write(f"{infl}\t{initial_pos}\t{initial_ud}\n")
                    f.flush()
        for entry in discard_entries:
            f.write(f"{entry}\n")
            f.flush()
    print(f"Done! decoding took {1000*(time.perf_counter()-tic):.2f}ms", file=sys.stderr)

if __name__ == "__main__":
    main()
